import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Brain Rotinator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <head></head>
      <body className={`${inter.className} h-full bg-gradient-loop`}>
        {children}
        <Suspense fallback={null}></Suspense>
      </body>
    </html>
  );
}
